# Build settings
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from

# Site settings
title: "KangSan Lee"
description: "나의 잡다한 공간"
email: ''
#blog logo
logo: "/assets/images/profile.jpg"
# blog cover
cover: "/assets/images/cover.jpg"

authors:
   KangSan Lee:
     name: KangSan Lee
     image: /assets/images/profile.jpg

paginate: 5

url: "http://kangsLee.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@lkasng'

#fill in disqus shortname to use disqus
disqus: 'kangsanlee'

timezone: Asia/Seoul

# social icons and sharing options
social:

  - icon: facebook
    url: http://fb.me/yikasa
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon: github
    url:  https://github.com/kangsLee
    desc: Our GitHub
    share_url:
    share_title:
    share_link:
